### ISSUE TITLE
Unit test never completes when collecting Flow

### ISSUE THREAD

**Issue by charlie-niekirk** [orbit-mvi/orbit-mvi#128]
I'm attempting to assert state changes when a certain intent is invoked.

This is my relevant testing code:

```kotlin
private val getCryptoAssetsUseCase = mockk<GetCryptoAssetsUseCase>()
private val testCoroutineDispatcher = StandardTestDispatcher()
private val assetName = "Bitcoin"
private val pagingData = PagingData.from(listOf(Asset(name = assetName)))

@Before
fun setUp() {
    coEvery { getCryptoAssetsUseCase() } returns(flowOf(pagingData))
}

@Test
fun getCryptoList_producesCorrectState() = runTest {
    val initialState = CryptoListState()
    val viewModel = CryptoListViewModel(getCryptoAssetsUseCase, testCoroutineDispatcher).test(
        initialState = initialState
    )

    viewModel.runOnCreate()

    viewModel.assert(initialState) {
        states(
            { copy(loading = true) },
            { copy(list = pagingData, loading = false) }
        )
    }
}
```

And this is my VM code:

```kotlin
@HiltViewModel
class CryptoListViewModel @Inject constructor(
    private val getCryptoAssetsUseCase: GetCryptoAssetsUseCase,
    @IoDispatcher private val coroutineDispatcher: CoroutineDispatcher
) : ContainerHost<CryptoListState, CryptoListSideEffect>, ViewModel() {

    override val container = container<CryptoListState, CryptoListSideEffect>(CryptoListState()) {
        getCryptoList()
    }

    private fun getCryptoList() = intent(registerIdling = false) {
        reduce { state.copy(loading = true) }
        withContext(coroutineDispatcher) {
            getCryptoAssetsUseCase().cachedIn(viewModelScope).collect {
                reduce { state.copy(list = it, loading = false) }
            }
        }
    }

    fun userSelectedAsset(assetName: String) = intent {
        postSideEffect(CryptoListSideEffect.NavigateToAssetDetail(assetName))
    }
}
```

However the test just hangs and never completes. I'm sure there's something funky I need to do with the `testCoroutineDispatcher` or something to force the `Flow` to complete, I'm just not sure what I'm doing wrong.

**Comment by kalpesh83** [comment]
I have had the same issue. The `Flows` are hot observables and in order to listen to new values they are `suspended`, hence they are always active. If you look at the example below, the last `println` statement is never executed. This is also the reason we always need separate `launch` blocks to collect different flows. 
```
val flow = MutableSharedFlow<Int>()
viewModelScope.launch {
    println("Before collect flow statement")
    flow.collect {
        println("Value: $it")
    }
    println("After collect flow statement")
}
```

A simple solution here would be collecting the flows like this:
```
val flow = MutableSharedFlow<Int>()
intent {
    println("Before collect flow statement")
    flow.onEach {
        println("Value: $it")
    }.flowOn(dispatchers.default) // use dispatcher that fits your requirement
        .launchIn(viewModelScope)
    println("After collect flow statement")
}
```
Both the `println` statements will be executed now because the `launchIn` function creates a new coroutine internally.

This is not the ideal solution. The `intent` blocks are executed in a blocking manner in MVI-Orbit when running unit tests. By creating different launch blocks on different scopes the UTCs work fine.

**Comment by Rosomack** [comment]
@charlie-niekirk I've created a simple test to check that the problem is not in `orbit` and I don't think there is an issue there.

``` kotlin
@Test
    fun `created does not hang`() = runBlocking {

        val someFlow = flowOf(1, 2, 3, 4)
        val testSubject = TestMiddleware(someFlow)

        val testContainerHost = testSubject.test()

        testContainerHost.runOnCreate()

        testContainerHost.assert(State(42)) {
            states(
                { copy(count = 1) },
                { copy(count = 2) },
                { copy(count = 3) },
                { copy(count = 4) }
            )
        }
    }

    private inner class TestMiddleware(val flow: Flow<Int>) :
        ContainerHost<State, Nothing> {
        override val container = scope.container<State, Nothing>(State()) {
            created()
        }

        fun created() = intent {
            withContext(Dispatchers.Default) {
                flow.collect {
                    reduce { state.copy(count = it) }
                }
            }
        }
    }

    private data class State(val count: Int = 42)
```

The above test completes successfully. 

Keep in mind that by default Orbit runs the scheduled intents in situ, within the test coroutine. Any internal orbit dispatch is bypassed to simplify testing.

The trick to successfully testing flows with Orbit is ensuring two things:

1. The flow is finite. This ensures that after all emissions are collected the test can complete.
2. Using testing dispatchers etc. correctly - as we all know it can be difficult. Coroutine testing can be notoriously hard.

In your case, the problem is likely (2). I'm not sure what the exact cause is. When I modify the test to use the `StandardTestDispatcher` it works when I also set `Main` to the same dispatcher (otherwise I get Kotlin complaining about `Detected use of different schedulers.` - although this might be down to my testing environment).

**Comment by kenyee** [comment]
Could you update the docs to tell folks to avoid this pattern in the viewmodel?

```
 init {
        viewModelScope.launch {
            employeeRepository.employeesFlow.collect {
                handleRepositoryUpdate(it)
            }
        }
    }
```

Works fine when running, but tests are totally broken: state never gets collected.  Spent time debugging until I found this reported issue.
The docs also mention a "runOnSubscription" method that doesn't exist.
